Repository Mirix-Software/react-mirix, pull requests merged in 2025-03, with the labels that each got.

#4 ci(github-actions): setting github workflow and actions
  .github/CODEOWNERS.txt
  .github/workflows/auto-tag.yml
  .github/workflows/ci.yml
  .github/workflows/commit-message-and-branch-check.yml
  .github/workflows/label-check.yml
  .gitignore
  src/main.tsx
Labels: ci

#5 fix(исправить работу ci): ci
  .github/workflows/auto-tag.yml
Labels: ci

#6 ci: add auto-tag
  .github/workflows/auto-tag.yml
Labels: ci

#7 ci: add auto-tag
  .github/workflows/auto-tag.yml
  .github/workflows/ci.yml
Labels: ci

#8 ci(codeowners): add aerosstube
  .github/CODEOWNERS.txt
Labels: ci

#9 fix: fix actions
  .github/workflows/auto-tag.yml
Labels: ci

#10 ci: fix auto tag
  commitizen.js
  package.json
Labels: fix

#11 fix: another fix
  .github/workflows/auto-tag.yml
Labels: fix

#12 feat(player): Added player component
  components.json
  index.html
  package-lock.json
  package.json
  public/MIRIX.svg
  src/App.css
  src/app.tsx
  src/assets/react.svg
  src/components/controls/controls.tsx
  src/components/controls/index.ts
  src/components/player/index.ts
  src/components/player/player.tsx
  src/components/ui/button.tsx
  src/components/ui/index.ts
  src/components/ui/popover.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/scrubber/index.ts
  src/components/ui/scrubber/scrubber-time-display.tsx
  src/components/ui/scrubber/scrubber-track.tsx
  src/components/ui/scrubber/scrubber.tsx
  src/components/ui/slider.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/index.css
  src/lib/clamp.ts
  src/lib/format-time.ts
  src/lib/hls/hls-change-level.ts
  src/lib/hls/hls-init.ts
  src/lib/hls/index.ts
  src/lib/scrubber/get-position.ts
  src/lib/scrubber/get-time.ts
  src/lib/scrubber/index.ts
  src/lib/utils.ts
  src/main.tsx
  src/types/controls.types.ts
  src/types/index.ts
  src/types/player.types.ts
  src/types/ui.types.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: feature

#13 Added controls
  biome.json
  commitizen.cjs
  commitlint.config.cjs
  components.json
  package-lock.json
  package.json
  src/app.tsx
  src/assets/icons/backward.svg
  src/assets/icons/caption.svg
  src/assets/icons/caret.svg
  src/assets/icons/dub.svg
  src/assets/icons/forward.svg
  src/assets/icons/frame.svg
  src/assets/icons/maximize.svg
  src/assets/icons/minimize.svg
  src/assets/icons/next.svg
  src/assets/icons/pause.svg
  src/assets/icons/pip.svg
  src/assets/icons/play.svg
  src/assets/icons/playlist.svg
  src/assets/icons/previous.svg
  src/assets/icons/settings.svg
  src/assets/icons/share.svg
  src/assets/icons/speed.svg
  src/assets/icons/voiceover.svg
  src/assets/icons/volume.svg
  src/components/controls/controls.tsx
  src/components/player/player.tsx
  src/components/ui/button.tsx
  src/components/ui/icon.tsx
  src/components/ui/popover.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/scrubber/scrubber-time-display.tsx
  src/components/ui/scrubber/scrubber-track.tsx
  src/components/ui/scrubber/scrubber.tsx
  src/components/ui/slider.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/index.css
  src/lib/clamp.ts
  src/lib/debounce.ts
  src/lib/format-time.ts
  src/lib/hls/hls-change-level.ts
  src/lib/hls/hls-init.ts
  src/lib/scrubber/get-position.ts
  src/lib/scrubber/get-time.ts
  src/lib/utils.ts
  src/main.tsx
  src/types/controls.types.ts
  src/types/icon.types.ts
  src/types/index.ts
  src/types/player.types.ts
  src/types/ui.types.ts
  tsconfig.json
  vite.config.ts
Labels: feature

#14 Added favicon
  index.html
  public/favicon.svg
  public/vite.svg
Labels: feature

#15 Added volume slider
  src/app.tsx
Labels: feature

#16 ci(github): fix auto tags
  .github/workflows/auto-tag.yml
  .github/workflows/commit-message-and-branch-check.yml
Labels: breaking-changes

#17 feat(controls): Added volume hanlders
  package-lock.json
  src/app.tsx
  src/assets/icons/volume-half.svg
  src/assets/icons/volume-muted.svg
  src/assets/icons/volume-none.svg
  src/components/ui/button.tsx
  src/components/ui/popover.tsx
  src/components/ui/scrubber/scrubber-track.tsx
  src/components/ui/slider.tsx
  src/index.css
  src/lib/storage.ts
  src/types/icon.types.ts
Labels: feature
